version: '3.8'

services:
  db:
    image: postgres
    healthcheck:
      test: exit 0
    ports:
     - 5432:5432
    environment:
      - POSTGRES_DB=mx_schedule
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
  pilotapp_react:
    build: .
    image: samzr/pilotapp2:latest
    command: npm start
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432
      - NODE_ENV=test
    depends_on:
      - pilotapp_server
    ports:
      - 2003:3000

  pilotapp_server:
    build: .
    image: samzr/pilotapp_server2:latest
    command: npm start
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432
      - NODE_ENV=test
    depends_on:
      - db
    links:
      - db
    ports:
      - 8083:8083